### ISSUE TITLE
The last authMethod/authResult is shown twice in operation history

### ISSUE THREAD

**Issue by petrdvorak** [lime-company/lime-security-powerauth-webauth#44]
```json
"history": [
      {
        "authMethod": null,
        "authResult": "CONTINUE"
      },
      {
        "authMethod": "USERNAME_PASSWORD_AUTH",
        "authResult": "CONTINUE"
      },
      {
        "authMethod": "SHOW_OPERATION_DETAIL",
        "authResult": "CONTINUE"
      },
      {
        "authMethod": "POWERAUTH_TOKEN",
        "authResult": "DONE"
      },
      {
        "authMethod": "POWERAUTH_TOKEN",
        "authResult": "DONE"
      }
    ],
```

**Comment by romanstrobl** [comment]
I investigated the problem. It is caused by a duplicate call of method authorize:

1. The first call happens in MobileTokenController in method verifySignature():
final UpdateOperationResponse updateOperationResponse = authorize(operationId, userId);

When the POWERAUTH_TOKEN method is confirmed using authorize(), NS operation status is set to DONE. This is triggered by the user confirming the operation on the mobile device.

2. The second call happens in MobileTokenController in method checkOperationStatus():

Call of method buildAuthorizationResponse(..) leads to another call of authorize() method, which once again sets the operation status to DONE. This is triggered by the webauth mtoken step, after the 3s timeout and positive result of method authenticate().

There several possible solutions, each with some advantages and disadvantages:
1. NS can check whether an operation is already DONE and ignore all future updates to the history, just return that the operation is DONE. This is easy to do, but does not fix the cause (although it would work well in practice IMO). 
2. Another option is to check the operation status before calling the authorize() method in the buildAuthorizationResponse() method and if the operation is already DONE, bypass second authorize() call.
3. Best option IMO would be avoiding calling authorize() method twice - this is a bit tricky, because the first authorize() call causing DONE state comes from the mobile app and then the web app also wants to update the operation to DONE state.

**Comment by petrdvorak** [comment]
@romanstrobl Interesting... and thank you for investigation!

I think that the last option is the best, I will re-implement the `/authenticate` endpoint so that it does not call authorize on already authorized operation.

**Comment by romanstrobl** [comment]
Ok, great. I think we should handle this scenario on NS side, too. When a NS client tries to update a DONE operation, it will lead to an error (I think it's better than ignoring it). Agree?

**Comment by petrdvorak** [comment]
Yes, I agree. Next Step should generally check if the update calls made to it are legitimate...

**Comment by romanstrobl** [comment]
Ok, I raised #45 to track the legitimacy checks, we can add these checks once this issue is fixed (now it would break the second authorize() call).
